# Generated by Django 2.1 on 2018-08-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyhead',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
