# Generated by Django 2.1 on 2018-08-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0002_companyhead_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyhead',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_head',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_location',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.DeleteModel(
            name='CompanyHead',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
