# Generated by Django 2.1 on 2018-08-18 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openPW_REST_API', '0003_auto_20180818_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_location',
            field=models.CharField(max_length=90),
        ),
    ]
