# Generated by Django 2.1 on 2018-08-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0004_auto_20180818_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.EmailField(default=None, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_password',
            field=models.CharField(default=None, max_length=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_user',
            field=models.CharField(max_length=90, unique=True),
        ),
    ]
