# Generated by Django 2.1 on 2018-08-18 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0005_auto_20180818_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_user',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
