# Generated by Django 2.1 on 2018-08-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0006_auto_20180818_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_verified',
        ),
    ]
