# Generated by Django 2.1 on 2018-08-19 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0008_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
