# Generated by Django 2.1 on 2018-08-19 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0012_auto_20180819_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='productexchange',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='openPW_REST_API.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productexchange',
            name='target_company',
            field=models.CharField(default=None, max_length=90),
            preserve_default=False,
        ),
    ]
