# Generated by Django 2.1 on 2018-08-19 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0014_remove_productexchange_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expense', models.FloatField(default=None, max_length='30')),
                ('total_sale', models.FloatField(default=None, max_length='30')),
                ('gain', models.FloatField(default=None, max_length='30')),
                ('loss', models.FloatField(default=None, max_length='30')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openPW_REST_API.Company')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openPW_REST_API.Product')),
            ],
        ),
    ]
