# Generated by Django 2.1 on 2018-08-21 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0018_auto_20180821_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='trans_date',
            new_name='trans_datetime',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='product',
            name='datetime_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
