# Generated by Django 2.1 on 2018-08-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0024_auto_20180826_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequest',
            name='product',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='target_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openPW_REST_API.Product'),
        ),
    ]
