# Generated by Django 2.1 on 2018-08-26 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0025_auto_20180826_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_company', models.CharField(max_length=90)),
                ('product', models.CharField(max_length=90)),
                ('trans_datetime', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openPW_REST_API.Company')),
            ],
        ),
        migrations.RemoveField(
            model_name='productexchange',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productexchange',
            name='product',
        ),
        migrations.RemoveField(
            model_name='traderequest',
            name='company',
        ),
        migrations.RemoveField(
            model_name='traderequest',
            name='target_product',
        ),
        migrations.DeleteModel(
            name='ProductExchange',
        ),
        migrations.DeleteModel(
            name='TradeRequest',
        ),
    ]
