# Generated by Django 2.1 on 2018-08-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0026_auto_20180826_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='company',
        ),
        migrations.AddField(
            model_name='productrequest',
            name='company',
            field=models.ManyToManyField(to='openPW_REST_API.Company'),
        ),
    ]
