# Generated by Django 2.1 on 2018-08-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0027_auto_20180826_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='company',
        ),
        migrations.AddField(
            model_name='productrequest',
            name='company',
            field=models.CharField(default=None, max_length=90),
            preserve_default=False,
        ),
    ]
