# Generated by Django 2.1 on 2018-08-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0029_auto_20180826_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='company',
            field=models.CharField(max_length=90),
        ),
    ]
