# Generated by Django 2.1 on 2018-08-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0030_auto_20180826_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openPW_REST_API.Company'),
        ),
    ]
