# Generated by Django 2.1 on 2018-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openPW_REST_API', '0032_auto_20180826_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='product',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='requesting_company',
            field=models.IntegerField(),
        ),
    ]
